using System.Security.Cryptography;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace AdenRising.Updater.Core;

/// <summary>
/// The envelope a signed release document arrives in. See tools/signing.mjs
/// for the other end.
/// </summary>
public sealed record SignedEnvelope(
    [property: JsonPropertyName("alg")] string Alg,
    [property: JsonPropertyName("keyId")] string KeyId,
    [property: JsonPropertyName("payload")] string Payload,
    [property: JsonPropertyName("signature")] string Signature);

/// <summary>What was signed: which kind of document, when, and the document itself.</summary>
public sealed record SignedPayload(
    [property: JsonPropertyName("kind")] string Kind,
    [property: JsonPropertyName("issuedAt")] string IssuedAt,
    [property: JsonPropertyName("body")] JsonElement Body);

/// <summary>
/// Why the launcher can trust what it downloads.
///
/// The client manifest and the launcher's own release note come from a bucket
/// behind a CDN. Every one of those is somebody else's machine, and a bucket
/// key, a Cloudflare login or a DNS record are all things that can leak. So
/// nothing that arrives is acted on until it proves it was signed by the
/// release key, which never leaves the owner's hands. A host that is
/// compromised can then withhold an update; it cannot forge one.
///
/// ECDSA P-256 over the exact payload bytes. The public key is compiled in;
/// there is no way to swap it short of a new launcher, which itself has to
/// arrive signed.
/// </summary>
public static class Signing
{
    /// <summary>Base64 SubjectPublicKeyInfo of the release key. Generated by
    /// tools/release-keys.mjs; tools/public/release-signing.pub holds the same
    /// value so `release-keys.mjs check` can tell them apart.</summary>
    public const string PublicKey = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEX55YXiROdA8arnY1QQL8xvHC5e5EwvFq5I8SG55BamBHKu2CVrI8MhS1jDftgL4GoPnlpaVE/VfbybdE/TSp7w==";

    /// <summary>Envelopes bigger than this are not something we publish.</summary>
    public const int MaxEnvelopeBytes = 16 * 1024 * 1024;

    private static readonly JsonSerializerOptions Options = new() { PropertyNameCaseInsensitive = true };

    /// <summary>
    /// Opens an envelope: checks the signature, then that it was signed as
    /// <paramref name="kind"/>. Throws on anything it does not like -- the
    /// callers all treat that as "no update today".
    /// </summary>
    public static SignedPayload Open(string json, string kind)
    {
        if (string.IsNullOrEmpty(PublicKey))
            throw new InvalidOperationException("this launcher was built without a release key");
        if (json.Length > MaxEnvelopeBytes)
            throw new InvalidDataException("the envelope is larger than any we publish");

        var envelope = JsonSerializer.Deserialize<SignedEnvelope>(json, Options)
            ?? throw new InvalidDataException("empty envelope");
        if (envelope.Alg != "ES256")
            throw new InvalidDataException($"unsupported algorithm {envelope.Alg}");

        var payload = Convert.FromBase64String(envelope.Payload);
        var signature = Convert.FromBase64String(envelope.Signature);

        using var key = ECDsa.Create();
        key.ImportSubjectPublicKeyInfo(Convert.FromBase64String(PublicKey), out _);
        if (!key.VerifyData(payload, signature, HashAlgorithmName.SHA256, DSASignatureFormat.IeeeP1363FixedFieldConcatenation))
            throw new InvalidDataException("the signature is not the release key's");

        var inner = JsonSerializer.Deserialize<SignedPayload>(payload, Options)
            ?? throw new InvalidDataException("empty payload");
        if (!inner.Kind.Equals(kind, StringComparison.Ordinal))
            throw new InvalidDataException($"signed as {inner.Kind}, not {kind}");
        if (!DateTimeOffset.TryParse(inner.IssuedAt, null, System.Globalization.DateTimeStyles.RoundtripKind, out _))
            throw new InvalidDataException("no issue date");

        return inner;
    }
}

/// <summary>
/// The newest issue date accepted for each kind of document, so a copy of an
/// older signed document -- genuine, but superseded -- cannot be served in
/// place of the current one. A rollback we mean is republished, and so
/// re-signed with a fresh date, by the tools.
///
/// Per user rather than per game folder: it is about which releases this
/// person has already seen.
/// </summary>
public static class TrustLog
{
    private static string Path_ => Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Aden Rising", "trust.json");

    private static Dictionary<string, string> Read()
    {
        try
        {
            if (!File.Exists(Path_)) return new();
            return JsonSerializer.Deserialize<Dictionary<string, string>>(File.ReadAllText(Path_)) ?? new();
        }
        catch { return new(); }
    }

    /// <summary>Throws when <paramref name="issuedAt"/> is older than the last one accepted for this kind.</summary>
    public static void RequireNotOlder(string kind, string issuedAt)
    {
        var offered = DateTimeOffset.Parse(issuedAt, null, System.Globalization.DateTimeStyles.RoundtripKind);
        if (Read().TryGetValue(kind, out var seen)
            && DateTimeOffset.TryParse(seen, null, System.Globalization.DateTimeStyles.RoundtripKind, out var last)
            && offered < last)
            throw new InvalidDataException($"a {kind} issued {offered:u} is older than the one already accepted ({last:u})");
    }

    /// <summary>Remembers that a document with this issue date was acted on.</summary>
    public static void Accept(string kind, string issuedAt)
    {
        try
        {
            var all = Read();
            all[kind] = issuedAt;
            Directory.CreateDirectory(Path.GetDirectoryName(Path_)!);
            File.WriteAllText(Path_, JsonSerializer.Serialize(all));
        }
        catch { /* forgetting is safe: it only means an older document could be accepted again */ }
    }
}
